server:
  port: 8083

spring:
  application:
    name: user-service

  datasource:
    master:
      jdbc-url: ${DB_URL_USER}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 10
        minimum-idle: 5
        idle-timeout: 300000  # 5분
        connection-timeout: 20000  # 20초
        pool-name: MasterHikariPool

    slave:
      jdbc-url: ${DB_URL_USER_SLAVE}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 20
        minimum-idle: 10
        idle-timeout: 300000
        connection-timeout: 20000
        pool-name: SlaveHikariPool

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
      auth-code-expiration-millis: 180000 # 3분


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true

jwt:
  secret:
    key: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

logging:
  level:
    root: info
  config: classpath:logback-user.xml

kakao:
  client_id: ${KAKAO_CLIENT_ID}
  redirect_uri: ${REDIRECT_URL}

