server:
  port: 8082

spring:
  application:
    name: reservation-service

  # Bean 오버라이딩 허용 설정 추가
  main:
    allow-bean-definition-overriding: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL_RESERVATION}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false

  kafka:
    bootstrap-servers: ${KAFKA_SERVER}
    topic:
      payment-events: payment-events
      reservation-events: reservation-events
    consumer:
      group-id: notification-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

payment:
  toss:
    url: ${PAYMENT_URL}
    test_client_api_key: ${PAYMENT_CLIENT_KEY}
    test_secret_api_key: ${PAYMENT_SECRET_KEY}
    success_url: ${PAYMENT_SUCCESS_URL}
    fail_url: ${PAYMENT_FAIL_URL}

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

logging:
  level:
    root: info
  config: classpath:logback-reservation.xml