server:
  port: 8082

spring:
  application:
    name: reservation-service

  # Bean 오버라이딩 허용 설정 추가
  main:
    allow-bean-definition-overriding: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://13.124.17.212:3306/reservation?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false

  kafka:
    bootstrap-servers: localhost:9092
    topic:
      payment-events: payment-events
      reservation-events: reservation-events
    consumer:
      group-id: notification-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

payment:
  toss:
    url: "https://api.tosspayments.com/v1/payments"
    test_client_api_key: test_ck_d46qopOB896o7NDMkGm73ZmM75y0
    test_secret_api_key: test_sk_zXLkKEypNArWmo50nX3lmeaxYG5R
    success_url: "http://localhost:8080/api/v1/payments/toss/success"
    fail_url: "http://localhost:8080/api/v1/payments/toss/fail"

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

logging:
  level:
    root: info
  config: classpath:logback-reservation.xml