server:
  port: 8081

spring:
  application:
    name: concert-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://13.124.17.212:3306/concert?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
  data:
    redis:
      host: 13.124.17.212
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

logging:
  level:
    root: info
  config: classpath:logback-concert.xml