server:
  port: 8081

spring:
  application:
    name: concert-service
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    master:
      jdbc-url: ${DB_URL_CONCERT}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 10
        minimum-idle: 5
        idle-timeout: 300000  # 5분
        connection-timeout: 20000  # 20초
        pool-name: MasterHikariPool

    slave:
      jdbc-url: ${DB_URL_CONCERT_SLAVE}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 20
        minimum-idle: 10
        idle-timeout: 300000
        connection-timeout: 20000
        pool-name: SlaveHikariPool

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  kafka:
    bootstrap-servers: ${KAFKA_SERVER}
    producer:
      retries: 3
      acks: all
      max-in-flight-requests-per-connection: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: concert-group
    topic:
      reservation-created: seat.reservation.created
      reservation-created-compensation: seat.reservation.created.compensation
      concert-updated: concert.updated
  elasticsearch:
    uris: ${ELASTICSEARCH_URL}
    username: ${ELASTICSEARCH_NAME}
    password: ${ELASTICSEARCH_PASSWORD}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}  # AWS 비밀 키
    region:
      static: ${AWS_REGION}  # AWS 리전
    s3:
      bucket: ${AWS_S3_BUCKET}  # S3 버킷 이름
    stack:
      auto: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

logging:
  level:
    root: info
  config: classpath:logback-concert.xml

webhooks:
  url: ${WEBHOOKS_URL}

resilience4j.circuitbreaker:
  instances:
    reservationService:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
