server:
  port: 8081

spring:
  application:
    name: concert-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: ${DB_URL_CONCERT}
    url: jdbc:mysql://localhost:3306/concertservice
#    username: ${DB_USERNAME}
    username: root
#    password: ${DB_PASSWORD}
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
  data:
    redis:
#      host: ${REDIS_HOST}
#      port: ${REDIS_PORT}
      host: localhost
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
feign:
  client:
    config:
      default:
        loadbalancer: true

logging:
  level:
    root: info
  config: classpath:logback-concert.xml