pipeline {
    agent any
    environment {
        DOCKER_IMAGE = "your-dockerhub-username/batch-service"
        // Redis
        REDIS_HOST = credentials('REDIS_HOST')
        REDIS_PORT = credentials('REDIS_PORT')
        // Database
        DB_URL_BATCH = credentials('DB_URL_BATCH')
        DB_USER = credentials('DB_USER')
        DB_PASSWORD = credentials('DB_PASSWORD')
        // Eureka
        EUREKA_URL = credentials('EUREKA_URL')
    }
    stages {
        stage('Check Branch') {
            when {
                branch 'main'
            }
            steps {
                echo "Push event detected on 'main' branch"
            }
        }
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: "your-git-repository-url"
            }
        }
        stage('Grant Execute Permission') {
            steps {
                sh 'chmod +x gradlew'
            }
        }
        stage('Build Project') {
            steps {
                sh './gradlew clean build -x test'
            }
        }
        stage('Build and Push Docker Image') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'docker-credentials', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                        sh '''
                            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                            docker build -t $DOCKER_IMAGE .
                            docker push $DOCKER_IMAGE
                        '''
                    }
                }
            }
        }
        stage('Deploy') {
            steps {
                sh '''
                    docker stop batch-service || true
                    docker rm batch-service || true
                    docker run -d --name batch-service -p 8089:8089 \
                    -e REDIS_HOST=$REDIS_HOST \
                    -e REDIS_PORT=$REDIS_PORT \
                    -e DB_URL_BATCH=$DB_URL_BATCH \
                    -e DB_USER=$DB_USER \
                    -e DB_PASSWORD=$DB_PASSWORD \
                    -e EUREKA_URL=$EUREKA_URL \
                    $DOCKER_IMAGE
                '''
            }
        }
    }
    post {
        always {
            sh 'docker logout'
        }
        failure {
            emailext (
                subject: "Pipeline Failed: ${currentBuild.fullDisplayName}",
                body: "Pipeline failure in ${env.BUILD_URL}",
                recipientProviders: [[$class: 'DevelopersRecipientProvider']]
            )
        }
    }
}